name: kyabnaye
description: "kya-bnaye: what should I cook today"
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.4
  kya_core:
    path: ../packages/kya_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
